#!/usr/bin/env bash
# script that transfer file from client to server
# -i s4: the path to private key, s1: file to be transferred
# s3: username s4: ip address
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
