#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service restart nginx
