#!/usr/bin/env bash
# installing nginx
# updating app
sudo apt-get update
# installing nginx
sudo apt-get install nginx -y
# enable NGINX
sudo ufw allow "Nginx HTTP"
create a static page
echo "Hello World!" | sudo tee /var/www/html/index.html
# restart server
sudo service nginx restart