#!/usr/bin/env bash
# Make to /redirect_me is redirecting to another page.


# Installing nginx
sudo apt-get update
sudo apt-get install -y nginx

# Adding Html page
echo "Hello World" | sudo tee /var/www/html/index.html

# Configuring firewall
ufw allow 'Nginx HTTP'

#redirecting a permanet move (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/tijesus permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# test
sudo nginx -t

# Restarting
service nginx restart
