#!/usr/bin/env bash
# Redirection - replaceing file with multiple line 
#Redirection for code error 
sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="string_to_replace;\n\trewrite ^\/redirect_me https:\/\/github.com\/tijesus permanent;"
sudo sed -i "s/string_to_replace;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default


# restart server
sudo service nginx restart
