#!/usr/bin/env bash
# debugging nginx port 80 by deleting and replacing file

# -s represent symbolic link and -f is used to delete the replaced file 
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
