#!/usr/bin/env bash
# printing best school 10 times

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
        echo "Best School"

    else
        echo "Best School"
    fi
    ((i++))
done
