#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
# apache may interfere with nginx so kill the process if it is running
pkill apache2
# replace port 80 with 8080 in the sites-available config
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# now start the nginx service with the new nginx user
sudo -u nginx service nginx restart
